# Generated by Django 5.2.7 on 2025-10-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_image_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
