# Generated by Django 5.2.7 on 2025-10-02 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ACCEPTED', 'Accepted'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_duration_months', models.IntegerField()),
                ('request_sent_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orderrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UPCOMING', 'Upcoming'), ('PENDING', 'Pending')], default='UPCOMING', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='order.orderrequest')),
            ],
        ),
    ]
